package io.bioimage.modelrunner.model.python.methods;

import java.util.UUID;

public class ConvertDims {

	final private static String METHOD_NAME = "convert_dims_" + UUID.randomUUID().toString().replace("-", "_");

	final private static String METHOD_DECLARATION = ""
			+ "def " + METHOD_NAME + "(" + System.lineSeparator()
			+ "    x," + System.lineSeparator()
			+ "    in_order: str," + System.lineSeparator()
			+ "    *," + System.lineSeparator()
			+ "    out_order: str = \"bcyx\"," + System.lineSeparator()
			+ "    n_channels: int = 3," + System.lineSeparator()
			+ "    drop_index: int = 0," + System.lineSeparator()
			+ "    dtype=None," + System.lineSeparator()
			+ "    device=None," + System.lineSeparator()
			+ "    contiguous: bool = True," + System.lineSeparator()
			+ "    output_type: str = \"torch\"," + System.lineSeparator()
			+ "):" + System.lineSeparator()
			+ "    \"\"\"Convert an array/tensor between axis orders, returning NumPy or Torch.\"\"\"" + System.lineSeparator()
			+ "    def _normalize_order(order: str, name: str) -> str:" + System.lineSeparator()
			+ "        if not isinstance(order, str) or not order.strip():" + System.lineSeparator()
			+ "            raise ValueError(f\"{name} must be a non-empty string\")" + System.lineSeparator()
			+ "        order = order.lower().replace(\" \", \"\")" + System.lineSeparator()
			+ "        if not all(ch.isalpha() for ch in order):" + System.lineSeparator()
			+ "            raise ValueError(f\"{name}='{order}' must contain only letters\")" + System.lineSeparator()
			+ "        if len(set(order)) != len(order):" + System.lineSeparator()
			+ "            raise ValueError(f\"{name}='{order}' contains repeated axes\")" + System.lineSeparator()
			+ "        return order" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    def _dtype_to_numpy(dtype_value):" + System.lineSeparator()
			+ "        if dtype_value is None:" + System.lineSeparator()
			+ "            return None" + System.lineSeparator()
			+ "        try:" + System.lineSeparator()
			+ "            return np.dtype(dtype_value)" + System.lineSeparator()
			+ "        except TypeError:" + System.lineSeparator()
			+ "            pass" + System.lineSeparator()
			+ "        name = str(dtype_value).lower().replace('torch.', '').replace('numpy.', '').replace('np.', '')" + System.lineSeparator()
			+ "        aliases = {" + System.lineSeparator()
			+ "            'float': 'float32', 'float32': 'float32', 'float64': 'float64', 'double': 'float64'," + System.lineSeparator()
			+ "            'float16': 'float16', 'half': 'float16', 'uint8': 'uint8', 'int8': 'int8'," + System.lineSeparator()
			+ "            'int16': 'int16', 'short': 'int16', 'int32': 'int32', 'int': 'int32'," + System.lineSeparator()
			+ "            'int64': 'int64', 'long': 'int64', 'bool': 'bool'" + System.lineSeparator()
			+ "        }" + System.lineSeparator()
			+ "        return np.dtype(aliases.get(name, name))" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    in_order = _normalize_order(in_order, \"in_order\")" + System.lineSeparator()
			+ "    out_order = _normalize_order(out_order, \"out_order\")" + System.lineSeparator()
			+ "    output_type = str(output_type).lower().strip()" + System.lineSeparator()
			+ "    if output_type not in (\"torch\", \"tensor\", \"numpy\", \"np\"):" + System.lineSeparator()
			+ "        raise ValueError(f\"output_type must be 'torch' or 'numpy', got {output_type!r}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    want_torch = output_type in (\"torch\", \"tensor\")" + System.lineSeparator()
			+ "    x = np.asarray(x)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if x.ndim != len(in_order):" + System.lineSeparator()
			+ "        raise ValueError(f\"in_order='{in_order}' has {len(in_order)} dims, but x.ndim={x.ndim}\")" + System.lineSeparator()
			+ "    if n_channels < 1 and 'c' in out_order:" + System.lineSeparator()
			+ "        raise ValueError(f\"n_channels must be >= 1, got {n_channels}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    for i in range(len(in_order) - 1, -1, -1):" + System.lineSeparator()
			+ "        if in_order[i] not in out_order:" + System.lineSeparator()
			+ "            idx = drop_index if drop_index >= 0 else drop_index + x.shape[i]" + System.lineSeparator()
			+ "            if not (0 <= idx < x.shape[i]):" + System.lineSeparator()
			+ "                raise IndexError(" + System.lineSeparator()
			+ "                    f\"drop_index={drop_index} out of range for axis '{in_order[i]}' \"" + System.lineSeparator()
			+ "                    f\"at dim {i} with size {x.shape[i]}\"" + System.lineSeparator()
			+ "                )" + System.lineSeparator()
			+ "            x = np.take(x, idx, axis=i)" + System.lineSeparator()
			+ "            in_order = in_order[:i] + in_order[i + 1:]" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    for ax in out_order:" + System.lineSeparator()
			+ "        if ax not in in_order:" + System.lineSeparator()
			+ "            x = np.expand_dims(x, axis=-1)" + System.lineSeparator()
			+ "            in_order += ax" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    perm = [in_order.index(ax) for ax in out_order]" + System.lineSeparator()
			+ "    if perm != list(range(len(perm))):" + System.lineSeparator()
			+ "        x = np.transpose(x, perm)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if \"c\" in out_order:" + System.lineSeparator()
			+ "        c_idx = out_order.index(\"c\")" + System.lineSeparator()
			+ "        c = x.shape[c_idx]" + System.lineSeparator()
			+ "        if c != n_channels:" + System.lineSeparator()
			+ "            if c == 1:" + System.lineSeparator()
			+ "                shape = list(x.shape)" + System.lineSeparator()
			+ "                shape[c_idx] = n_channels" + System.lineSeparator()
			+ "                x = np.broadcast_to(x, shape)" + System.lineSeparator()
			+ "            elif c < n_channels:" + System.lineSeparator()
			+ "                reps = [1] * x.ndim" + System.lineSeparator()
			+ "                reps[c_idx] = (n_channels + c - 1) // c" + System.lineSeparator()
			+ "                x = np.tile(x, reps)" + System.lineSeparator()
			+ "                x = np.take(x, range(n_channels), axis=c_idx)" + System.lineSeparator()
			+ "            else:" + System.lineSeparator()
			+ "                x = np.take(x, range(n_channels), axis=c_idx)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if dtype is None:" + System.lineSeparator()
			+ "        dtype = np.float32" + System.lineSeparator()
			+ "    if want_torch:" + System.lineSeparator()
			+ "        np_dtype = _dtype_to_numpy(dtype)" + System.lineSeparator()
			+ "        x = x.astype(np_dtype, copy=False)" + System.lineSeparator()
			+ "        if contiguous:" + System.lineSeparator()
			+ "            x = np.ascontiguousarray(x)" + System.lineSeparator()
			+ "        x = torch.as_tensor(x)" + System.lineSeparator()
			+ "        if device is not None:" + System.lineSeparator()
			+ "            x = x.to(device=device, non_blocking=True)" + System.lineSeparator()
			+ "        return x" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    dtype = _dtype_to_numpy(dtype)" + System.lineSeparator()
			+ "    x = x.astype(dtype, copy=False)" + System.lineSeparator()
			+ "    return np.ascontiguousarray(x) if contiguous else x" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "" + System.lineSeparator();

	public static String getMethodName() {
		return METHOD_NAME;
	}

	public static String getMethodDeclaration() {
		return METHOD_DECLARATION;
	}
}
