package io.bioimage.modelrunner.model.python.methods;

import java.util.UUID;

public class ConvertDims {
	
	final private static String METHOD_NAME = "convert_dims_" + UUID.randomUUID().toString().replace("-", "_");
	
	final private static String METHOD_DECLARATION = ""
			+ "def " + METHOD_NAME + "(" + System.lineSeparator()
			+ "    x," + System.lineSeparator()
			+ "    in_order: str," + System.lineSeparator()
			+ "    *," + System.lineSeparator()
			+ "    out_order: str = \"bcyx\"," + System.lineSeparator()
			+ "    n_channels: int = 3," + System.lineSeparator()
			+ "    drop_index: int = 0," + System.lineSeparator()
			+ "    dtype: torch.dtype = torch.float32," + System.lineSeparator()
			+ "    device=None," + System.lineSeparator()
			+ "    contiguous: bool = True," + System.lineSeparator()
			+ "):" + System.lineSeparator()
			+ "    \"\"\"" + System.lineSeparator()
			+ "    Convert an array/tensor from arbitrary input axis order to arbitrary output axis order." + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    Rules" + System.lineSeparator()
			+ "    -----" + System.lineSeparator()
			+ "    - `in_order` and `out_order` are strings with one letter per axis." + System.lineSeparator()
			+ "    - Axes present in `in_order` but not in `out_order` are dropped by taking `drop_index`." + System.lineSeparator()
			+ "    - Axes present in `out_order` but not in `in_order` are added as singleton dims." + System.lineSeparator()
			+ "    - If 'c' is in `out_order`, channels are adapted to `n_channels`." + System.lineSeparator()
			+ "    - Normalization is optional." + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    Examples" + System.lineSeparator()
			+ "    --------" + System.lineSeparator()
			+ "    \"hw\"      -> \"bchw\"" + System.lineSeparator()
			+ "    \"whc\"     -> \"bchw\"" + System.lineSeparator()
			+ "    \"bzhwc\"   -> \"bchw\"   (drops z)" + System.lineSeparator()
			+ "    \"hw\"      -> \"hwc\"    (adds singleton c)" + System.lineSeparator()
			+ "    \"czhw\"    -> \"bhwc\"   (adds singleton b, reorders)" + System.lineSeparator()
			+ "    \"\"\"" + System.lineSeparator()
			+ "    def _normalize_order(order: str, name: str) -> str:" + System.lineSeparator()
			+ "        if not isinstance(order, str) or not order.strip():" + System.lineSeparator()
			+ "            raise ValueError(f\"{name} must be a non-empty string\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        order = order.lower().replace(\" \", \"\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if not all(ch.isalpha() for ch in order):" + System.lineSeparator()
			+ "            raise ValueError(f\"{name}='{order}' must contain only letters\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if len(set(order)) != len(order):" + System.lineSeparator()
			+ "            raise ValueError(f\"{name}='{order}' contains repeated axes\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        return order" + System.lineSeparator()
			+ "    x = torch.as_tensor(x)" + System.lineSeparator()
			+ "    in_order = _normalize_order(in_order, \"in_order\")" + System.lineSeparator()
			+ "    out_order = _normalize_order(out_order, \"out_order\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if x.ndim != len(in_order):" + System.lineSeparator()
			+ "        raise ValueError(f\"in_order='{in_order}' has {len(in_order)} dims, but x.ndim={x.ndim}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if n_channels < 1 and 'c' in out_order:" + System.lineSeparator()
			+ "        raise ValueError(f\"n_channels must be >= 1, got {n_channels}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    # Drop axes not needed in the output, right-to-left so indices stay valid." + System.lineSeparator()
			+ "    for i in range(len(in_order) - 1, -1, -1):" + System.lineSeparator()
			+ "        if in_order[i] not in out_order:" + System.lineSeparator()
			+ "            idx = drop_index if drop_index >= 0 else drop_index + x.shape[i]" + System.lineSeparator()
			+ "            if not (0 <= idx < x.shape[i]):" + System.lineSeparator()
			+ "                raise IndexError(" + System.lineSeparator()
			+ "                    f\"drop_index={drop_index} out of range for axis '{in_order[i]}' \"" + System.lineSeparator()
			+ "                    f\"at dim {i} with size {x.shape[i]}\"" + System.lineSeparator()
			+ "                )" + System.lineSeparator()
			+ "            x = x.select(i, idx)" + System.lineSeparator()
			+ "            in_order = in_order[:i] + in_order[i + 1:]" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    # Add missing output axes as singleton dims." + System.lineSeparator()
			+ "    for ax in out_order:" + System.lineSeparator()
			+ "        if ax not in in_order:" + System.lineSeparator()
			+ "            x = x.unsqueeze(-1)" + System.lineSeparator()
			+ "            in_order += ax" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    # Reorder once into the requested output layout." + System.lineSeparator()
			+ "    perm = [in_order.index(ax) for ax in out_order]" + System.lineSeparator()
			+ "    x = x.permute(*perm)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    # Adapt channels only if the output has a channel axis." + System.lineSeparator()
			+ "    if \"c\" in out_order:" + System.lineSeparator()
			+ "        c_idx = out_order.index(\"c\")" + System.lineSeparator()
			+ "        c = x.shape[c_idx]" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if c != n_channels:" + System.lineSeparator()
			+ "            if c == 1:" + System.lineSeparator()
			+ "                # grayscale -> N channels by replication" + System.lineSeparator()
			+ "                shape = list(x.shape)" + System.lineSeparator()
			+ "                shape[c_idx] = n_channels" + System.lineSeparator()
			+ "                x = x.expand(*shape)" + System.lineSeparator()
			+ "            elif c < n_channels:" + System.lineSeparator()
			+ "                reps = [1] * x.ndim" + System.lineSeparator()
			+ "                reps[c_idx] = (n_channels + c - 1) // c" + System.lineSeparator()
			+ "                x = x.repeat(*reps)" + System.lineSeparator()
			+ "                x = x.narrow(c_idx, 0, n_channels)" + System.lineSeparator()
			+ "            else:" + System.lineSeparator()
			+ "                x = x.narrow(c_idx, 0, n_channels)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if device is None:" + System.lineSeparator()
			+ "        x = x.to(dtype=dtype)" + System.lineSeparator()
			+ "    else:" + System.lineSeparator()
			+ "        x = x.to(device=device, dtype=dtype, non_blocking=True)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if contiguous:" + System.lineSeparator()
			+ "        x = x.contiguous()" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    return x" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "" + System.lineSeparator();
	
	public static String getMethodName() {
		return METHOD_NAME;
	}
	
	public static String getMethodDeclaration() {
		return METHOD_DECLARATION;
	}

}
