package io.bioimage.modelrunner.model.python.methods;

import java.util.UUID;

public class LetterboxPreprocessing {
	
	private static final String METHOD_NAME = "letterbox_preprocessing_" + UUID.randomUUID().toString().replace("-", "_");
	
	private static final String METHOD_DECLARATION = ""
			+ "import torch" + System.lineSeparator()
			+ "import torch.nn.functional as F" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "def " + METHOD_NAME + "(" + System.lineSeparator()
			+ "    x: torch.Tensor," + System.lineSeparator()
			+ "    *," + System.lineSeparator()
			+ "    target_max_side: int = 640," + System.lineSeparator()
			+ "    stride: int = 32," + System.lineSeparator()
			+ "    padding_value: float = 114.0," + System.lineSeparator()
			+ "    center: bool = True," + System.lineSeparator()
			+ "    scaleup: bool = True," + System.lineSeparator()
			+ "    contiguous: bool = True," + System.lineSeparator()
			+ "):" + System.lineSeparator()
			+ "    \"\"\"" + System.lineSeparator()
			+ "    Apply YOLO-style minimal letterbox preprocessing to a PyTorch tensor." + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    Assumptions" + System.lineSeparator()
			+ "    -----------" + System.lineSeparator()
			+ "    - Input must already be in PyTorch spatial order:" + System.lineSeparator()
			+ "      - BCYX  -> shape (B, C, Y, X)" + System.lineSeparator()
			+ "      - BCZYX -> shape (B, C, Z, Y, X)" + System.lineSeparator()
			+ "    - No axis reordering is performed." + System.lineSeparator()
			+ "    - No normalization is performed." + System.lineSeparator()
			+ "    - No channel manipulation is performed." + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    Behavior" + System.lineSeparator()
			+ "    --------" + System.lineSeparator()
			+ "    - Resizes so the largest spatial side becomes `target_max_side`" + System.lineSeparator()
			+ "    - Preserves aspect ratio" + System.lineSeparator()
			+ "    - Pads only Y/X so they are divisible by `stride`" + System.lineSeparator()
			+ "    - For BCZYX, applies the same resize/pad to every Z slice" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    Returns" + System.lineSeparator()
			+ "    -------" + System.lineSeparator()
			+ "    x_out : torch.Tensor" + System.lineSeparator()
			+ "    meta : dict with:" + System.lineSeparator()
			+ "        - scale" + System.lineSeparator()
			+ "        - resized_hw" + System.lineSeparator()
			+ "        - pad = (top, bottom, left, right)" + System.lineSeparator()
			+ "        - original_hw" + System.lineSeparator()
			+ "        - final_hw" + System.lineSeparator()
			+ "    \"\"\"" + System.lineSeparator()
			+ "    if not isinstance(x, torch.Tensor):" + System.lineSeparator()
			+ "        x = torch.as_tensor(x)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if x.ndim not in (4, 5):" + System.lineSeparator()
			+ "        raise ValueError(" + System.lineSeparator()
			+ "            f\"Input tensor must be BCYX (4D) or BCZYX (5D), got shape {tuple(x.shape)}\"" + System.lineSeparator()
			+ "        )" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if target_max_side < 1:" + System.lineSeparator()
			+ "        raise ValueError(f\"target_max_side must be >= 1, got {target_max_side}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if stride < 1:" + System.lineSeparator()
			+ "        raise ValueError(f\"stride must be >= 1, got {stride}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if x.ndim == 4:  # BCYX" + System.lineSeparator()
			+ "        _, _, y, xdim = x.shape" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        scale = target_max_side / max(y, xdim)" + System.lineSeparator()
			+ "        if not scaleup:" + System.lineSeparator()
			+ "            scale = min(scale, 1.0)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        new_y = int(round(y * scale))" + System.lineSeparator()
			+ "        new_x = int(round(xdim * scale))" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        x_out = F.interpolate(x, size=(new_y, new_x), mode=\"bilinear\", align_corners=False)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        pad_y = (stride - new_y % stride) % stride" + System.lineSeparator()
			+ "        pad_x = (stride - new_x % stride) % stride" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if center:" + System.lineSeparator()
			+ "            top = pad_y // 2" + System.lineSeparator()
			+ "            bottom = pad_y - top" + System.lineSeparator()
			+ "            left = pad_x // 2" + System.lineSeparator()
			+ "            right = pad_x - left" + System.lineSeparator()
			+ "        else:" + System.lineSeparator()
			+ "            top = 0" + System.lineSeparator()
			+ "            bottom = pad_y" + System.lineSeparator()
			+ "            left = 0" + System.lineSeparator()
			+ "            right = pad_x" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if pad_y or pad_x:" + System.lineSeparator()
			+ "            x_out = F.pad(x_out, (left, right, top, bottom), value=padding_value)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    else:  # BCZYX" + System.lineSeparator()
			+ "        b, c, z, y, xdim = x.shape" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        scale = target_max_side / max(y, xdim)" + System.lineSeparator()
			+ "        if not scaleup:" + System.lineSeparator()
			+ "            scale = min(scale, 1.0)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        new_y = int(round(y * scale))" + System.lineSeparator()
			+ "        new_x = int(round(xdim * scale))" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        x_work = x.permute(0, 2, 1, 3, 4).reshape(b * z, c, y, xdim)" + System.lineSeparator()
			+ "        x_work = F.interpolate(x_work, size=(new_y, new_x), mode=\"bilinear\", align_corners=False)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        pad_y = (stride - new_y % stride) % stride" + System.lineSeparator()
			+ "        pad_x = (stride - new_x % stride) % stride" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if center:" + System.lineSeparator()
			+ "            top = pad_y // 2" + System.lineSeparator()
			+ "            bottom = pad_y - top" + System.lineSeparator()
			+ "            left = pad_x // 2" + System.lineSeparator()
			+ "            right = pad_x - left" + System.lineSeparator()
			+ "        else:" + System.lineSeparator()
			+ "            top = 0" + System.lineSeparator()
			+ "            bottom = pad_y" + System.lineSeparator()
			+ "            left = 0" + System.lineSeparator()
			+ "            right = pad_x" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if pad_y or pad_x:" + System.lineSeparator()
			+ "            x_work = F.pad(x_work, (left, right, top, bottom), value=padding_value)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        out_y = new_y + pad_y" + System.lineSeparator()
			+ "        out_x = new_x + pad_x" + System.lineSeparator()
			+ "        x_out = x_work.reshape(b, z, c, out_y, out_x).permute(0, 2, 1, 3, 4)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if contiguous:" + System.lineSeparator()
			+ "        x_out = x_out.contiguous()" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    meta = {" + System.lineSeparator()
			+ "        \"scale\": scale," + System.lineSeparator()
			+ "        \"resized_hw\": (new_y, new_x)," + System.lineSeparator()
			+ "        \"pad\": (top, bottom, left, right)," + System.lineSeparator()
			+ "        \"original_hw\": (y, xdim)," + System.lineSeparator()
			+ "        \"final_hw\": (new_y + pad_y, new_x + pad_x)," + System.lineSeparator()
			+ "    }" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    return x_out, meta";
	
	public static String getMethodName() {
		return METHOD_NAME;
	}
	
	public static String getMethodDeclaration() {
		return METHOD_DECLARATION;
	}

}
