package io.bioimage.modelrunner.model.python.methods;

import java.util.UUID;

public class UndoLetterboxProcessingBoundingBoxes {
	
	private static final String METHOD_NAME = "undo_letterbox_preprocessing_bboxes_" + UUID.randomUUID().toString().replace("-", "_");
	
	private static final String METHOD_DECLARATION = ""
			+ "import numpy as np" + System.lineSeparator()
			+ "import torch" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "def " + METHOD_NAME + "(boxes, meta, *, clip: bool = True, copy: bool = True):" + System.lineSeparator()
			+ "    \"\"\"" + System.lineSeparator()
			+ "    Undo YOLO letterbox preprocessing on BN6 detections." + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    Parameters" + System.lineSeparator()
			+ "    ----------" + System.lineSeparator()
			+ "    boxes : torch.Tensor or np.ndarray" + System.lineSeparator()
			+ "        Shape (B, N, 6), where the last dimension is:" + System.lineSeparator()
			+ "        [x1, y1, x2, y2, conf, cls]" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        The xyxy coordinates must be in the letterboxed image coordinate system." + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    meta : dict or sequence of dict" + System.lineSeparator()
			+ "        Metadata returned by yolo_letterbox_torch()." + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        Accepted forms:" + System.lineSeparator()
			+ "        - single dict: same letterbox metadata applied to the whole batch" + System.lineSeparator()
			+ "        - sequence of length B: one meta dict per batch item" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        Required keys in each dict:" + System.lineSeparator()
			+ "        - \"scale\": float" + System.lineSeparator()
			+ "        - \"pad\": (top, bottom, left, right)" + System.lineSeparator()
			+ "        - \"original_hw\": (orig_y, orig_x)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    clip : bool" + System.lineSeparator()
			+ "        If True, clip coordinates to the original image bounds." + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    copy : bool" + System.lineSeparator()
			+ "        If True, return a copy." + System.lineSeparator()
			+ "        If False, modify the input in place when possible." + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    Returns" + System.lineSeparator()
			+ "    -------" + System.lineSeparator()
			+ "    same type as `boxes`" + System.lineSeparator()
			+ "        BN6 detections with xyxy mapped back to the original image coordinates." + System.lineSeparator()
			+ "    \"\"\"" + System.lineSeparator()
			+ "    is_torch = isinstance(boxes, torch.Tensor)" + System.lineSeparator()
			+ "    is_numpy = isinstance(boxes, np.ndarray)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if not (is_torch or is_numpy):" + System.lineSeparator()
			+ "        raise TypeError(f\"boxes must be torch.Tensor or np.ndarray, got {type(boxes)}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if boxes.ndim != 3 or boxes.shape[-1] != 6:" + System.lineSeparator()
			+ "        raise ValueError(f\"boxes must have shape (B, N, 6), got {tuple(boxes.shape)}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    out = boxes.clone() if (is_torch and copy) else (boxes.copy() if (is_numpy and copy) else boxes)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    b = out.shape[0]" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    if isinstance(meta, dict):" + System.lineSeparator()
			+ "        metas = [meta] * b" + System.lineSeparator()
			+ "    else:" + System.lineSeparator()
			+ "        metas = list(meta)" + System.lineSeparator()
			+ "        if len(metas) != b:" + System.lineSeparator()
			+ "            raise ValueError(f\"meta sequence length must match batch size {b}, got {len(metas)}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    for i in range(b):" + System.lineSeparator()
			+ "        m = metas[i]" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if \"scale\" not in m or \"pad\" not in m or \"original_hw\" not in m:" + System.lineSeparator()
			+ "            raise ValueError(\"Each meta dict must contain 'scale', 'pad', and 'original_hw'\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        scale = float(m[\"scale\"])" + System.lineSeparator()
			+ "        top, bottom, left, right = m[\"pad\"]" + System.lineSeparator()
			+ "        orig_y, orig_x = m[\"original_hw\"]" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if scale <= 0:" + System.lineSeparator()
			+ "            raise ValueError(f\"Invalid scale={scale}\")" + System.lineSeparator()
			+ "        if orig_y <= 0 or orig_x <= 0:" + System.lineSeparator()
			+ "            raise ValueError(f\"Invalid original_hw={m['original_hw']}\")" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        # Undo padding" + System.lineSeparator()
			+ "        out[i, :, 0] = (out[i, :, 0] - left) / scale   # x1" + System.lineSeparator()
			+ "        out[i, :, 2] = (out[i, :, 2] - left) / scale   # x2" + System.lineSeparator()
			+ "        out[i, :, 1] = (out[i, :, 1] - top) / scale    # y1" + System.lineSeparator()
			+ "        out[i, :, 3] = (out[i, :, 3] - top) / scale    # y2" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "        if clip:" + System.lineSeparator()
			+ "            if is_torch:" + System.lineSeparator()
			+ "                out[i, :, 0].clamp_(0, orig_x)" + System.lineSeparator()
			+ "                out[i, :, 2].clamp_(0, orig_x)" + System.lineSeparator()
			+ "                out[i, :, 1].clamp_(0, orig_y)" + System.lineSeparator()
			+ "                out[i, :, 3].clamp_(0, orig_y)" + System.lineSeparator()
			+ "            else:" + System.lineSeparator()
			+ "                out[i, :, 0] = np.clip(out[i, :, 0], 0, orig_x)" + System.lineSeparator()
			+ "                out[i, :, 2] = np.clip(out[i, :, 2], 0, orig_x)" + System.lineSeparator()
			+ "                out[i, :, 1] = np.clip(out[i, :, 1], 0, orig_y)" + System.lineSeparator()
			+ "                out[i, :, 3] = np.clip(out[i, :, 3], 0, orig_y)" + System.lineSeparator()
			+ "" + System.lineSeparator()
			+ "    return out";
	
	public static String getMethodName() {
		return METHOD_NAME;
	}
	
	public static String getMethodDeclaration() {
		return METHOD_DECLARATION;
	}

}
