name: Bioimage.io CI

concurrency:
  group: test-resources
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      pending_matrix:
        description: 'json encoded gh matrix of pending validations for new or updated resources (default: test on all resources)'
        required: true
        default: '{"include": [{"resource_id": "**", "version_id": "**"}]}'
        type: string


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version_matrix: ${{ steps.cvm.outputs.version_matrix }}
      pending_empty: ${{ steps.pending_empty.outputs.is_empty }}

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: bioimage-io/collection-bioimage-io
        ref: gh-pages
        path: bioimageio-gh-pages
    - name: Print pending_matrix
      run: echo "Pending Matrix: ${{ github.event.inputs.pending_matrix }}"
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@< version >
      with:
        java-version: 11
        maven-version: 3.9.5
    - name: test with JDLL
      shell: bash -l {0}
      run: python scripts/test_many_with_ilastik.py dist '${{ github.event.inputs.pending_matrix }}' --postfix ${{ matrix.v }}
    - name: Upload test summaries
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.v }}
        path: dist
        retention-days: 1

  deploy:
    needs: [run]
    if: needs.setup.outputs.pending_empty == 'no'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: merge ilastik test summaries  # (they differ by postfix)
      run: |
        mkdir dist
        cp -r artifacts/*/* dist
    - name: Deploy test summaries to gh-pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        clean: false
        branch: gh-pages
        folder: dist
