name: Download all engines
on:
  push:
    branches:
      - main
    paths:
      - src/main/resources/availableDLVersions.json
      - download-engines.py
      - .github/workflows/download_all_engines.yml
  pull_request:
    branches: [ main ]
jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] # macos-10.15,
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Download all engines
      run: |
        python download-engines.py
