name: Run Pytorch model
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] # macos-10.15,
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Build with Maven
      run: mvn install
    - name: Run ExampleLoadAndRunModel.java file
      shell: bash
      run: |
        if [[ "$OSTYPE" == "win"* ]]; then
          java -cp  target\\classes io.bioimage.modelrunner.example.ExampleLoadAndRunModel
        else
          java -cp  target/classes io.bioimage.modelrunner.example.ExampleLoadAndRunModel
        fi
