name: Get jar sizes
on:
  push:
    branches:
      - main
    paths:
      - src/main/resources/availableDLVersions.json
      - .github/workflows/jar_sizes.yml
      - .github/get_jar_sizes.py
  workflow_dispatch:
  
  
env:
  FPATH: "src/main/resources/jar_sizes.json"
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Get file sizes and generate JSON
        run: |
          ls
          python .github/get_jar_sizes.py ${{ env.FPATH }}

      - name: Commit and push changes
        run: |
          # Configure Git
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Only commit/push if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git add ${{ env.FPATH }}
            git commit -m "Update file sizes"
            git push
          else
            echo "No changes to commit."
          fi
