name: TEst arm64
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Build with Maven
      run: mvn clean install
      
    - name: Generate Classpath (Unix)
      if: runner.os != 'Windows'
      run: echo "CLASSPATH=$(mvn -q exec:exec -Dexec.executable=echo -Dexec.args='%classpath')" >> $GITHUB_ENV

    - name: Run ExampleLoadAndRunAllBmzModels.java (Unix)
      if: runner.os != 'Windows'
      run: java -cp $CLASSPATH:target/classes io.bioimage.modelrunner.versionmanagement.SupportedVersions
